In [436]:
tabs.to_csv('EDA_PROJECT_MAIN.csv')
tabs.to_excel('EDA_PROJECT_MAIN.xlsx')

In [376]:
import pandas as pd 
tabs = pd.read_csv('EDA_PROJECT_MAIN.csv')

In [377]:
tabs

,Unnamed: 0,Product_name,Price,Ram,Rating,Count_Rating,Review,Inch,Battery,Colour,Android_IOS
0,0,REDMI Pad Pro 5G,"₹22,999",8 GB,4.4,"6,726",432,12.1,10000.0,Graphite Grey,Android 14
1,1,Samsung Galaxy Tab A9+,"₹21,999",8 GB,4.5,"38,465","1,473",11.0,7040.0,Graphite,Android 12
2,2,POCO Pad 5G,"₹21,999",8 GB,4.4,"9,167",749,12.1,10000.0,Cobalt Blue,Android 14
3,3,Samsung Galaxy Tab A9,"₹15,999",4 GB,4.3,"2,393",102,8.7,5100.0,Navy,Android 12
4,4,Samsung Galaxy Tab A9+,"₹24,999",8 GB,4.5,"38,465","1,473",11.0,7040.0,Navy,Android 12
...,...,...,...,...,...,...,...,...,...,...,...
403,403,Samsung Galaxy Tab A9+,"₹16,999",4 GB,4.5,"38,465","1,473",11.0,5100.0,GRAPHITE,Android 12
404,404,Samsung Galaxy Tab A9+,"₹17,999",8 GB,4.5,"38,465","1,473",11.0,5100.0,Silver,Android 12
405,405,Samsung Galaxy Tab A9+,"₹16,999",8 GB,4.5,"38,465","1,473",11.0,5100.0,Navy,Android 12
406,406,Samsung Galaxy Tab A9,"₹12,490",4 GB,4.3,"2,393",102,8.7,5100.0,Graphite,Android 12
407,407,Samsung Galaxy Tab A9+,"₹15,999",4 GB,4.5,"38,465","1,473",11.0,5100.0,Navy,Android 12

In [378]:
tabs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 408 entries, 0 to 407
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    408 non-null    int64
 1   Product_name  408 non-null    object
 2   Price         408 non-null    object
 3   Ram           255 non-null    object
 4   Rating        380 non-null    float64
 5   Count_Rating  380 non-null    object
 6   Review        380 non-null    object
 7   Inch          368 non-null    float64
 8   Battery       194 non-null    float64
 9   Colour        345 non-null    object
 10  Android_IOS   370 non-null    object
dtypes: float64(3), int64(1), object(7)
memory usage: 35.2+ KB

In [379]:
tabs = tabs.drop(columns=['Unnamed: 0'])

In [380]:
tabs

,Product_name,Price,Ram,Rating,Count_Rating,Review,Inch,Battery,Colour,Android_IOS
0,REDMI Pad Pro 5G,"₹22,999",8 GB,4.4,"6,726",432,12.1,10000.0,Graphite Grey,Android 14
1,Samsung Galaxy Tab A9+,"₹21,999",8 GB,4.5,"38,465","1,473",11.0,7040.0,Graphite,Android 12
2,POCO Pad 5G,"₹21,999",8 GB,4.4,"9,167",749,12.1,10000.0,Cobalt Blue,Android 14
3,Samsung Galaxy Tab A9,"₹15,999",4 GB,4.3,"2,393",102,8.7,5100.0,Navy,Android 12
4,Samsung Galaxy Tab A9+,"₹24,999",8 GB,4.5,"38,465","1,473",11.0,7040.0,Navy,Android 12
...,...,...,...,...,...,...,...,...,...,...
403,Samsung Galaxy Tab A9+,"₹16,999",4 GB,4.5,"38,465","1,473",11.0,5100.0,GRAPHITE,Android 12
404,Samsung Galaxy Tab A9+,"₹17,999",8 GB,4.5,"38,465","1,473",11.0,5100.0,Silver,Android 12
405,Samsung Galaxy Tab A9+,"₹16,999",8 GB,4.5,"38,465","1,473",11.0,5100.0,Navy,Android 12
406,Samsung Galaxy Tab A9,"₹12,490",4 GB,4.3,"2,393",102,8.7,5100.0,Graphite,Android 12
407,Samsung Galaxy Tab A9+,"₹15,999",4 GB,4.5,"38,465","1,473",11.0,5100.0,Navy,Android 12

In [381]:
tabs["Price"] = tabs["Price"].str.replace("₹","").str.replace("," ,"")

In [382]:
tabs["Price"] = tabs["Price"].astype("int")

In [383]:
tabs['Rating'] = tabs['Rating'].fillna("0")

In [384]:
tabs['Rating'] = tabs['Rating'].astype("float")

In [385]:
tabs["Rating"] = tabs["Rating"].replace(0,4.6)

In [386]:
tabs['Inch'] = tabs['Inch'].fillna(0)

In [387]:
tabs['Inch'] = tabs['Inch'].replace(0,9.9)

In [388]:
tabs['Ram'] = tabs['Ram'].fillna("0")

In [389]:
tabs["Ram"] = tabs["Ram"].str.replace("GB","")

In [390]:
tabs["Ram"] = tabs["Ram"].astype("int")

In [391]:
tabs['Count_Rating'] = tabs['Count_Rating'].fillna("0")

In [392]:
tabs['Count_Rating'] = tabs['Count_Rating'].str.replace(",","")

In [393]:
tabs['Review'] = tabs['Review'].str.replace(",","")

In [394]:
tabs['Count_Rating'] = tabs['Count_Rating'].astype("int")

In [395]:
tabs['Battery'] = tabs['Battery'].fillna(0)

In [396]:
tabs['Battery'] = tabs['Battery'].astype("int")

In [397]:
tabs['Brand'] = tabs['Product_name'].str.extract(r'^([A-Za-z]+)')

In [399]:
tabs

,Product_name,Price,Ram,Rating,Count_Rating,Review,Inch,Battery,Colour,Android_IOS,Brand
0,REDMI Pad Pro 5G,22999,8,4.4,6726,432,12.1,10000,Graphite Grey,Android 14,REDMI
1,Samsung Galaxy Tab A9+,21999,8,4.5,38465,1473,11.0,7040,Graphite,Android 12,Samsung
2,POCO Pad 5G,21999,8,4.4,9167,749,12.1,10000,Cobalt Blue,Android 14,POCO
3,Samsung Galaxy Tab A9,15999,4,4.3,2393,102,8.7,5100,Navy,Android 12,Samsung
4,Samsung Galaxy Tab A9+,24999,8,4.5,38465,1473,11.0,7040,Navy,Android 12,Samsung
...,...,...,...,...,...,...,...,...,...,...,...
403,Samsung Galaxy Tab A9+,16999,4,4.5,38465,1473,11.0,5100,GRAPHITE,Android 12,Samsung
404,Samsung Galaxy Tab A9+,17999,8,4.5,38465,1473,11.0,5100,Silver,Android 12,Samsung
405,Samsung Galaxy Tab A9+,16999,8,4.5,38465,1473,11.0,5100,Navy,Android 12,Samsung
406,Samsung Galaxy Tab A9,12490,4,4.3,2393,102,8.7,5100,Graphite,Android 12,Samsung
407,Samsung Galaxy Tab A9+,15999,4,4.5,38465,1473,11.0,5100,Navy,Android 12,Samsung

In [156]:
tabs[tabs['Product_name'] == 'Samsung Galaxy M17 5G']

,Product_name,Price,Ram,Rating,Count_Rating,Review,Inch,Battery,Colour,Android_IOS,Brand
247,Samsung Galaxy M17 5G,15103,0,4.2,10,1,9.9,5000,NaN,NaN,Samsung
252,Samsung Galaxy M17 5G,13534,0,4.0,5,0,9.9,5000,NaN,NaN,Samsung
253,Samsung Galaxy M17 5G,13470,0,4.0,5,0,9.9,5000,NaN,NaN,Samsung
313,Samsung Galaxy M17 5G,16999,0,4.0,3,1,9.9,5000,NaN,NaN,Samsung
406,Samsung Galaxy M17 5G,16999,0,4.0,3,1,9.9,5000,NaN,NaN,Samsung

In [297]:
tabs['Product_name'] .unique()

array(['REDMI  Pad Pro 5G', 'Samsung Galaxy Tab A9+', 'POCO Pad 5G',
       'Samsung Galaxy Tab A9', 'Samsung Galaxy Tab S9 FE',
       'Lenovo M10 5G', 'Samsung Galaxy Tab S9 FE+',
       'Samsung Galaxy Tab S10 FE', 'Samsung Galaxy Tab S11 Ultra',
       'Samsung Galaxy Tab A11', 'Apple iPad', 'Apple 2024 iPad Pro',
       'Apple 2022 iPad Pro', 'Samsung Galaxy Tab S11',
       'Samsung Galaxy Tab S10 FE+', 'Apple iPad mini',
       'Samsung Galaxy Tab S9', 'Apple iPad Air',
       'Samsung GalaxyTabA9+5g', 'Samsung Galaxy Tab S10 Ultra',
       'realme Pad X', 'Apple 2024 iPad Mini', 'Apple iPad Pro 2021',
       'Samsung SM-X216B', 'Lenovo Tab P11 5G', 'Apple 2024 iPad Air',
       'Samsung Galaxy Tab S9+', 'Apple 2025 iPad', 'Apple 2025 iPad Air',
       'Samsung Galaxy Tab S8+', 'Apple 2025 iPad Pro',
       'DRUMSTONE LearnTab 7-Inch Kids Learning Tablet',
       'Samsung Galaxy Tab S9 Ultra', 'OnePlus Pad Lite',
       'OnePlus Pad Go', 'realme Pad 2', 'Jio F320 B Lyf',
       'Infinix XPAD LTE',
       'Lenovo Chromebook Duet 11M889 MediaTek MediaTek Kompanio 838',
       'OPPO Pad SE', 'Lenovo Tab Plus', 'Lenovo Tab M9',
       'Samsung M36 5G', 'Samsung Galaxy M17 5G', 'Swipe STRIKE',
       'Samsung Galaxy Tab A8', 'Samsung Galaxy Tab A7 Lite',
       'DOMO SL39 OS9 3C', 'Samsung Galaxy Tab S8 Ultra',
       'Samsung Galaxy Tab S6 Lite', 'DOMO Tab SLP8 OS13',
       'DOMO Tab SLP9 6765 OS13', 'Acer Iconia Tab', 'TCL 10 TAB Max',
       'Xiaomi15', 'Samsung Galaxy Tab S10+', 'iball iTAB BizniZ Mini',
       'Samsung Galaxy Tab S7 FE', 'Apple iPad Pro 2020',
       'Wishtel IRA T1020', 'Lenovo Tab P11 Pro', 'Apple ipad Mini'],
      dtype=object)

In [298]:
tabs.loc[tabs['Product_name'] == 'Apple iPad', 'Battery'] = 7606

In [295]:
tabs["Brand"]=="Apple"

0      False
1      False
2      False
3      False
4      False
       ...
403    False
404    False
405    False
406    False
407    False
Name: Brand, Length: 408, dtype: bool

In [294]:
tabs[tabs["Product_name"]==10758]

Empty DataFrame
Columns: [Product_name, Price, Ram, Rating, Count_Rating, Review, Inch, Battery, Colour, Android_IOS, Brand]
Index: []

In [160]:
tabs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 408 entries, 0 to 407
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_name  408 non-null    object
 1   Price         408 non-null    int64
 2   Ram           408 non-null    int64
 3   Rating        408 non-null    float64
 4   Count_Rating  408 non-null    int64
 5   Review        381 non-null    object
 6   Inch          408 non-null    float64
 7   Battery       408 non-null    int64
 8   Colour        329 non-null    object
 9   Android_IOS   372 non-null    object
 10  Brand         406 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 35.2+ KB

In [161]:
tabs['Battery'] = tabs['Battery'].astype("int")

In [162]:
tabs

,Product_name,Price,Ram,Rating,Count_Rating,Review,Inch,Battery,Colour,Android_IOS,Brand
0,POCO Pad 5G,21999,8,4.4,9167,749,12.1,10000,Cobalt Blue,Android 14,POCO
1,REDMI Pad Pro 5G,22999,8,4.4,6726,432,12.1,10000,Graphite Grey,Android 14,REDMI
2,Samsung Galaxy Tab A9+,21999,8,4.5,38465,"1,473",11.0,7040,Graphite,Android 12,Samsung
3,Samsung Galaxy Tab A9,15999,4,4.3,2393,102,8.7,5100,Navy,Android 12,Samsung
4,Samsung Galaxy Tab A9+,24999,8,4.5,38465,"1,473",11.0,7040,Navy,Android 12,Samsung
...,...,...,...,...,...,...,...,...,...,...,...
403,Huawei MatePad T8 LTE,6999,2,3.8,474,44,9.9,5100,NaN,Android 10,Huawei
404,Samsung Galaxy Tab S9 FE+,45999,12,4.6,24848,"1,052",12.4,10090,Lavender,Android 12,Samsung
405,Samsung Galaxy Tab A9+,15999,4,4.5,38465,"1,473",11.0,5100,Navy,Android 12,Samsung
406,Samsung Galaxy M17 5G,16999,0,4.0,3,1,9.9,5000,NaN,NaN,Samsung
407,Samsung Galaxy Tab S9 FE,25999,6,4.5,4425,228,10.9,10090,Lavender,Android 12,Samsung

In [163]:
tabs['Battery'] = tabs['Battery'].fillna(0)

In [169]:
tabs['Product_name'].unique()

array(['POCO Pad 5G', 'REDMI  Pad Pro 5G', 'Samsung Galaxy Tab A9+',
       'Samsung Galaxy Tab A9', 'Samsung Galaxy Tab S9 FE',
       'Lenovo M10 5G', 'Samsung Galaxy Tab S9 FE+',
       'Samsung Galaxy Tab S10 FE', 'Samsung Galaxy Tab S11 Ultra',
       'Apple iPad', 'Apple 2024 iPad Pro', 'Apple 2022 iPad Pro',
       'Samsung Galaxy Tab S11', 'Samsung Galaxy Tab S10 FE+',
       'Apple iPad mini', 'Samsung Galaxy Tab S9', 'Apple iPad Air',
       'Samsung Galaxy Tab A11', 'Samsung GalaxyTabA9+5g',
       'Samsung Galaxy Tab S10 Ultra', 'realme Pad X', 'Samsung SM-X216B',
       'Apple 2024 iPad Mini', 'Apple iPad Pro 2021', 'Lenovo Tab P11 5G',
       'Samsung Galaxy Tab S9+', 'Apple 2025 iPad', 'Apple 2024 iPad Air',
       'Apple 2025 iPad Air', 'Samsung Galaxy Tab S8+',
       'Apple 2025 iPad Pro',
       'DRUMSTONE LearnTab 7-Inch Kids Learning Tablet',
       'Samsung Galaxy Tab S9 Ultra', 'Infinix XPAD LTE',
       'Lenovo Chromebook Duet 11M889 MediaTek MediaTek Kompanio 838',
       'Lenovo Tab Plus', 'Samsung M36 5G', 'Samsung Galaxy M17 5G',
       'Swipe STRIKE', 'Samsung Galaxy Tab A8', 'DOMO SL39 OS9 3C',
       'OnePlus Pad Lite', 'OnePlus Pad Go', 'realme Pad 2',
       'Jio F320 B Lyf', 'OPPO Pad SE', 'Tiitan SHIELD Tab White',
       'Redmi4', 'Samsung Galaxy Tab A7 LTE', 'Samsung Galaxy Tab A7',
       'LAVA Aura T81N UPGOVT', 'DOMO Slate Tab SSM28 OS13',
       'Samsung Galaxy Tab S7 FE', 'DOMO S10 DC OS9 Tab',
       'Micromax Canvas Tab P70221', 'Samsung Galaxy Tab S6 Lite',
       'Samsung Galaxy Tab A7 Lite', 'Samsung Galaxy Tab S8 Ultra',
       'DOMO Tab SLP8 OS13', 'DOMO Tab SLP9 6765 OS13', 'Acer Iconia Tab',
       'TCL 10 TAB Max', 'Xiaomi15', 'Samsung Galaxy Tab S10+',
       'iball iTAB BizniZ Mini', 10758, 'Lenovo Tab P11 Pro',
       'Apple ipad Mini', 'Huawei MatePad T8 LTE'], dtype=object)

In [ ]:
Apple iPad', 'Apple 2024 iPad Pro', 'Apple 2022 iPad Pro',
       'Apple iPad mini', 'Apple iPad Air', 'Apple 2024 iPad Mini',
       'Apple iPad Pro 2021', 'Apple 2025 iPad', 'Apple 2024 iPad Air',
       'Apple 2025 iPad Air', 'Apple 2025 iPad Pro',
       'Apple iPad Pro 2020', 'Apple ipad Mini'

In [ ]:
tabs['Inch'] = tabs['Inch'].replace(,9.9)

In [331]:
tabs.loc[tabs['Product_name'] == '']

,Product_name,Price,Ram,Rating,Count_Rating,Review,Inch,Battery,Colour,Android_IOS,Brand
201,DRUMSTONE LearnTab 7-Inch Kids Learning Tablet,6528,4,4.6,0,NaN,9.9,3000,NaN,NaN,DRUMSTONE

In [405]:
tabs.loc[tabs['Product_name'] ==  'Apple iPad', 'Battery'] = 7606

In [406]:
tabs.loc[tabs['Product_name'] ==  'Apple iPad Air', 'Battery'] = 7606

In [407]:
tabs.loc[tabs['Product_name'] ==  'Apple 2024 iPad Air', 'Battery'] = 7606

In [408]:
tabs.loc[tabs['Product_name'] ==  'Apple 2025 iPad Air', 'Battery'] = 7606

In [409]:
tabs.loc[tabs['Product_name'] == 'Apple 2024 iPad Pro', 'Battery'] = 7538

In [410]:
tabs.loc[tabs['Product_name'] ==  'Apple 2022 iPad Pro','Battery'] = 7538

In [411]:
tabs.loc[tabs['Product_name'] ==  'Apple iPad Pro 2021','Battery'] = 7538

In [412]:
tabs.loc[tabs['Product_name'] ==  'Apple 2025 iPad Pro','Battery'] = 7538

In [413]:
tabs.loc[tabs['Product_name'] ==  'Apple iPad mini','Battery'] = 5078

In [414]:
tabs.loc[tabs['Product_name'] ==  'Apple 2024 iPad Mini','Battery'] = 5078

In [415]:
tabs.loc[tabs['Product_name'] ==  'Apple ipad Mini','Battery'] = 5078

In [432]:
tabs.loc[tabs['Product_name'] ==  'Xiaomi15','Battery'] = 5000

In [425]:
tabs.loc[tabs['Product_name'] ==  'DRUMSTONE LearnTab 7-Inch Kids Learning Tablet','Battery'] = 3000

In [422]:
tabs.loc[tabs['Product_name'] ==  'Samsung Galaxy Tab A9+','Battery'] = 7040

In [423]:
tabs.loc[tabs['Product_name'] ==  'Samsung GalaxyTabA9+5g','Battery'] = 7040

In [427]:
tabs.loc[tabs['Product_name'] ==  'Lenovo Chromebook Duet 11M889 MediaTek MediaTek Kompanio 838','Battery'] = 3767

In [428]:
tabs.loc[tabs['Product_name'] ==  'Samsung M36 5G','Battery'] = 5000

In [430]:
tabs.loc[tabs['Product_name'] ==  'Lenovo Tab M9','Battery'] = 5100

In [419]:
tabs.loc[tabs['Product_name'] ==  'Apple iPad Pro 2020','Battery'] = 10758

In [433]:
tabs.loc[tabs['Product_name'] ==  'Samsung Galaxy M17 5G','Battery'] = 5000

In [420]:
tabs.loc[tabs['Product_name'] == 'Apple iPad Pro 2020']

,Product_name,Price,Ram,Rating,Count_Rating,Review,Inch,Battery,Colour,Android_IOS,Brand
373,Apple iPad Pro 2020,117899,6,4.7,839,85,9.9,10758,NaN,iPadOS 13.4,Apple
375,Apple iPad Pro 2020,126609,6,4.7,839,85,9.9,10758,NaN,iPadOS 13.4,Apple

In [ ]:
Samsung Galaxy M17 5G

In [402]:
tabs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 408 entries, 0 to 407
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_name  408 non-null    object
 1   Price         408 non-null    int64
 2   Ram           408 non-null    int64
 3   Rating        408 non-null    float64
 4   Count_Rating  408 non-null    int64
 5   Review        380 non-null    object
 6   Inch          408 non-null    float64
 7   Battery       408 non-null    int64
 8   Colour        345 non-null    object
 9   Android_IOS   370 non-null    object
 10  Brand         408 non-null    object
dtypes: float64(2), int64(4), object(5)
memory usage: 35.2+ KB

In [228]:
tabs['Brand'].unique()

array(['POCO', 'REDMI', 'Samsung', 'Lenovo', 'Apple', 'realme',
       'DRUMSTONE', 'Infinix', 'Swipe', 'DOMO', 'OnePlus', 'OPPO',
       'Tiitan', 'Redmi', 'LAVA', 'Micromax', 'Acer', 'TCL', 'Xiaomi',
       'iball', 'Huawei'], dtype=object)

In [243]:
count_zero = (tabs['Count_Rating'] == 0).sum()
print(count_zero)

27

In [248]:
tabs[['Brand','Count_Rating']]

       Brand  Count_Rating
0       POCO          9167
1      REDMI          6726
2    Samsung         38465
3    Samsung          2393
4    Samsung         38465
..       ...           ...
400   Huawei           474
401  Samsung         24848
402  Samsung         38465
403  Samsung             3
404  Samsung          4425

[405 rows x 2 columns]

In [260]:
tabs['Count_Rating']==0

0      False
1      False
2      False
3      False
4      False
       ...
332    False
333    False
334    False
335    False
336    False
Name: Count_Rating, Length: 337, dtype: bool

In [437]:
tabs[tabs['Battery']==0]

,Product_name,Price,Ram,Rating,Count_Rating,Review,Inch,Battery,Colour,Android_IOS,Brand
137,Apple 2025 iPad,47479,0,4.7,10452,584,11.0,0,Yellow,iPadOS 18,Apple
140,Apple 2025 iPad,76029,0,4.7,10452,584,11.0,0,Blue,iPadOS 18,Apple
145,Apple 2025 iPad,47479,0,4.7,10452,584,11.0,0,Blue,iPadOS 18,Apple
147,Apple 2025 iPad,47479,0,4.7,10452,584,11.0,0,Silver,iPadOS 18,Apple
159,Apple 2025 iPad,56999,0,4.7,10452,584,11.0,0,Silver,iPadOS 18,Apple
160,Apple 2025 iPad,56999,0,4.7,10452,584,11.0,0,Pink,iPadOS 18,Apple
162,Apple 2025 iPad,56999,0,4.7,10452,584,11.0,0,Blue,iPadOS 18,Apple
167,Apple 2025 iPad,56999,0,4.7,10452,584,11.0,0,Yellow,iPadOS 18,Apple
173,Apple 2025 iPad,76029,0,4.7,10452,584,11.0,0,Silver,iPadOS 18,Apple
285,Apple 2025 iPad,33499,0,4.7,10452,584,11.0,0,Silver,iPadOS 18,Apple
306,Apple 2025 iPad,33490,0,4.7,10452,584,11.0,0,Pink,iPadOS 18,Apple
311,Apple 2025 iPad,33900,0,4.7,10452,584,11.0,0,Blue,iPadOS 18,Apple

In [314]:
tabs['Battery'].unique()

array([10000,  7040,  5100, 10090,  7700,  8000, 11600,  7606,  7538,
        8400,  5078,     0, 11200,  8340,  7500,  9340,  8360,  7000,
        8600,  3000,  5020,  7400,  5000,  4000])

In [371]:
tabs['Battery']==0

0      False
1      False
2      False
3      False
4      False
       ...
400    False
401    False
402    False
403    False
404    False
Name: Battery, Length: 405, dtype: bool

In [417]:
tabs = tabs.drop([299]).reset_index(drop=True)

In [435]:
tabs

,Product_name,Price,Ram,Rating,Count_Rating,Review,Inch,Battery,Colour,Android_IOS,Brand
0,REDMI Pad Pro 5G,22999,8,4.4,6726,432,12.1,10000,Graphite Grey,Android 14,REDMI
1,Samsung Galaxy Tab A9+,21999,8,4.5,38465,1473,11.0,7040,Graphite,Android 12,Samsung
2,POCO Pad 5G,21999,8,4.4,9167,749,12.1,10000,Cobalt Blue,Android 14,POCO
3,Samsung Galaxy Tab A9,15999,4,4.3,2393,102,8.7,5100,Navy,Android 12,Samsung
4,Samsung Galaxy Tab A9+,24999,8,4.5,38465,1473,11.0,7040,Navy,Android 12,Samsung
...,...,...,...,...,...,...,...,...,...,...,...
402,Samsung Galaxy Tab A9+,16999,4,4.5,38465,1473,11.0,7040,GRAPHITE,Android 12,Samsung
403,Samsung Galaxy Tab A9+,17999,8,4.5,38465,1473,11.0,7040,Silver,Android 12,Samsung
404,Samsung Galaxy Tab A9+,16999,8,4.5,38465,1473,11.0,7040,Navy,Android 12,Samsung
405,Samsung Galaxy Tab A9,12490,4,4.3,2393,102,8.7,5100,Graphite,Android 12,Samsung
406,Samsung Galaxy Tab A9+,15999,4,4.5,38465,1473,11.0,7040,Navy,Android 12,Samsung